### ISSUE TITLE
let user handle isolation

### ISSUE THREAD

**Issue by FeliciousX** [cyclejs-community/cyclejs-modal#10]
currently, isolation is handled by modalify internally.

if we want to use `onionify` with custom lenses we can't.

proposal is to remove isolation and let the user pass in an already isolated component on their own in the `open` action stream.

thoughts? @jvanbruegge  

this suggestion is a breaking change tho..

**Comment by jvanbruegge** [comment]
I fully agree, maybe through another option on the `ModalAction`? wouldnt be a breaking change then

**Comment by FeliciousX** [comment]
I don't know if we should support automatic isolation at all though given the nature of `isolate` now

what if we just bump the version for breaking change?

**Comment by FeliciousX** [comment]
plus, the update for this is not hard, just have to import isolate and sprinkle it wherever they have the `{ type : 'open', component : isolate( Component ) }`

**Comment by jvanbruegge** [comment]
yeah, this is better, i agree
