### ISSUE TITLE
[Suggestion] modalify argument to use objects

### ISSUE THREAD

**Issue by FeliciousX** [cyclejs-community/cyclejs-modal#13]
breaking change suggestion..

modify modalify ( pun intended ) arguments to use object instead of a list

```javascript
modalify( app, {
  name : 'modal',
  center : true,
  modalContainerClass : 'some-extra-class',
  background : 'rgba(0,0,0,0.8)',
  zIndex : 500
})
```

it reads better than

```javascript
modalify( app, 'modal', true, 'why-this-string-here', 'rgba(0,0,0,0.6)', 500 )
```

you don't know what `modal` does. what `true` is.. and what `500` is for.. and the random string

**Comment by jvanbruegge** [comment]
I agree with you. The extra arguments are hacky and not good for documentation.
Related to #14, the name of the DOM key could also be an option
