### ISSUE TITLE
Listening to clicks on overlay

### ISSUE THREAD

**Issue by FeliciousX** [cyclejs-community/cyclejs-modal#18]
Currently there's no way of us to get the click event of the overlay.

I'm not sure how the implementation would look like but it would be nice if we are able to listen to clicks on the overlay and then react upon it ( like closing the modal when they click the overlay )

**Comment by FeliciousX** [comment]
i can imagine the API could either be in

A) the options when creating modalify like `modalify( App, { magic-click-to-close' : true } )`
B) being able to `sources.DOM.select( '.overlay' ).events( 'click' )`

**Comment by jvanbruegge** [comment]
You mean the background divs that are used to center the modal?

**Comment by FeliciousX** [comment]
> You mean the background divs that are used to center the modal?

yes

**Comment by jvanbruegge** [comment]
A is defenitly easier to implement than B, because the centering DOM is not part of the local DOM of your component. I do not think it is even possible to do B

**Comment by jvanbruegge** [comment]
I think this should be done, and even activated as default, because it is common and people expect this behavior

**Comment by FeliciousX** [comment]
about the modal options, sometimes you can have multiple modal in 1 app, and some of them might want to behave differently

for example, `modal A` might want to have a behaviour where clicking on the overlay closes the modal but `modal B` does not behave that way. If we put it in options then it will always be the same behaviour across all modals

**Comment by FeliciousX** [comment]
what if when we send the `open` type action to the modal sink, we also include `options/behavior` alongside `component` ? adding a 3rd key to the object

**Comment by FeliciousX** [comment]
something like 

```javascript
{
  type: 'open',
  component : isolate( ModalFoo ),
  options : {
    clickOverlayClose : true
  }
}
```

```javascript
{
  type: 'open',
  component : isolate( ModalBar ),
  options : {
    clickOverlayClose : false
  }
}
```

**Comment by jvanbruegge** [comment]
I actually thought this was what you meant, yeah, it would be per modal, still with `true` as default

**Comment by jvanbruegge** [comment]
Added this feature in version `5.3.0`
