### ISSUE TITLE
`background`, `containerClass` and `zindex` are ignored when `center` is false

### ISSUE THREAD

**Issue by atomrc** [cyclejs-community/cyclejs-modal#20]
The most important, for my use case, would be to have the `modalContainerClass` option used even with the `center: false` option. 

This way I would be able to handle all the positioning in my CSS files without having to manually wrap all my modals in a `<div class="my-modal-wrapper">` 

I believe it is just a matter of consuming the `modalContainerClass` option here 
https://github.com/cyclejs-community/cyclejs-modal/blob/7603c2cc499bfa77ad71de7c158bd16152ca627a/src/modalify.ts#L96

I'd be happy to create a PR

**Comment by jvanbruegge** [comment]
Yeah, please open a PR :)

**Comment by atomrc** [comment]
I'll add the `class`. But I am not sure about `background` and `zindex` as they can be handled in the css once the `class` is set on the wrapping div.
